default_language_version:
  python: python 3.9
default_stages: [commit, push]
repos:
-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v4.5.0
   hooks:
   -  id: check-yaml
   -  id: requirements-txt-fixer
   -  id: no-commit-to-branch
-  repo: https://github.com/pre-commit/mirrors-autopep8
   rev: 'v2.0.4'
   hooks:
   -  id: autopep8
-  repo: https://github.com/pycqa/isort
   rev: 5.12.0
   hooks:
   -  id: isort
-  repo: https://github.com/PyCQA/flake8
   rev: 7.0.0
   hooks:
   -  id: flake8