version: '3'

services:
  vk-bot:
    build: .
    env_file:
      - ./.env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - 80:80
      - 443:443
    restart: always
    command: python3 /app/main.py
